// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

#include "../RobotMap.h"
#include "AutonomousCommand.h"

AutonomousCommand::AutonomousCommand() {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::drivetrain);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::drivetrain);
	leftEncoder = RobotMap::drivetrainQuadratureEncoderLeft;
	rightEncoder = RobotMap::drivetrainQuadratureEncoderRight;
}

// Called just before this Command runs the first time
void AutonomousCommand::Initialize() {

}

// Called repeatedly when this Command is scheduled to run
void AutonomousCommand::Execute() {
	Robot::drivetrain->TankDrive(-0.5,-0.5,false);
	//robot goes about 8ft in one second
	Wait (0.55); //goes 5 feet
	done = (true);
	//SmartDashboard::PutNumber("encoder", leftEncoder->GetDistance());
}

// Make this return true when this Command no longer needs to run execute()
bool AutonomousCommand::IsFinished() {
	return done;
}

// Called once after isFinished returns true
void AutonomousCommand::End() {
	Robot::drivetrain->TankDrive(0,0,false);
		done = false;
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void AutonomousCommand::Interrupted() {

}
